before_script:
  - apt-get update

after_script:
  - gradle --version

focal-jdk8:
  image: ubuntu:focal
  script:
    - apt-get -y install openjdk-8-jdk
    - apt-get -y install gradle
    - gradle build --stacktrace

focal-jdk11:
  image: ubuntu:focal
  script:
    - apt-get -y install openjdk-11-jdk
    - apt-get -y install gradle
    - gradle build --stacktrace
